<main>

<h3>comment utiliser ce forum ? </h3>
<p>Choisissez votre sujet de discussion en cliquant sur ceux qui vous sont présenté en haut de page.</p>
<p>Une fois choisi, vous aurez accès aux discussions de ce sujet comme présenté ci-dessous : </p>
<br><br><br>
<section class="message">
<div ><p class="message_user">Charles</p>
<p class="message_text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Libero expedita, nulla earum aspernatur quaerat aliquid maiores perspiciatis illum dignissimos? Facere cupiditate, esse similique harum vitae at impedit dolor reiciendis architecto quae maiores dolore distinctio rem maxime necessitatibus voluptatem. Officiis praesentium facilis expedita totam nemo, exercitationem voluptatibus, vitae blanditiis ratione, reprehenderit ea commodi perspiciatis maxime non natus harum id est molestiae. Non voluptas illum natus, ab voluptate debitis qui aut culpa, ratione inventore quasi minima ex quibusdam delectus asperiores deserunt quidem ea repellendus praesentium iusto quia nobis! Recusandae ipsum impedit nihil quo similique, quidem maxime illo quia adipisci aliquid ratione et unde expedita asperiores eaque commodi reiciendis vitae quos dolorum neque hic, perferendis accusamus corrupti. Debitis a, cupiditate omnis explicabo accusantium ea in molestias labore quibusdam ratione sint sed aliquid temporibus aliquam odit suscipit quaerat laborum nostrum eaque officia vel totam alias saepe incidunt! Earum, necessitatibus rem et veniam doloremque ducimus sunt quae dolorem ullam quod, vel temporibus modi. Porro nemo labore temporibus aspernatur pariatur et, nesciunt quaerat sequi corporis ex aliquam perspiciatis omnis optio dolore ipsa, laboriosam tempora dicta harum impedit. Sapiente rem impedit deleniti dolores ducimus architecto dolor, fugiat cupiditate delectus iure ea sequi hic repellat consequatur sit. Non amet praesentium debitis libero alias illo aspernatur, doloremque modi laudantium voluptatibus veritatis porro! Alias neque ducimus voluptas velit labore consequatur, atque cumque ratione a sunt ipsam sequi quia animi consectetur. Modi, ducimus asperiores fuga porro explicabo eos quidem nulla illum delectus laboriosam velit sint odit saepe recusandae omnis magni corporis.</p></div>
</section>

<section class="message">
<div ><p class="message_user">Eliott</p>
<p class="message_text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Libero expedita, nulla earum aspernatur quaerat aliquid maiores perspiciatis illum dignissimos? Facere cupiditate, esse similique harum vitae at impedit dolor reiciendis architecto quae maiores dolore distinctio rem maxime necessitatibus voluptatem. Officiis praesentium facilis expedita totam nemo, exercitationem voluptatibus, vitae blanditiis ratione, reprehenderit ea commodi perspiciatis maxime non natus harum id est molestiae. Non voluptas illum natus, ab voluptate debitis qui aut culpa, ratione inventore quasi minima ex quibusdam delectus asperiores deserunt quidem ea repellendus praesentium iusto quia nobis! Recusandae ipsum impedit nihil quo similique, quidem maxime illo quia adipisci aliquid ratione et unde expedita asperiores eaque commodi reiciendis vitae quos dolorum neque hic, perferendis accusamus corrupti. Debitis a, cupiditate omnis explicabo accusantium ea in molestias labore quibusdam ratione sint sed aliquid temporibus aliquam odit suscipit quaerat laborum nostrum eaque officia vel totam alias saepe incidunt! Earum, necessitatibus rem et veniam doloremque ducimus sunt quae dolorem ullam quod, vel temporibus modi. Porro nemo labore temporibus aspernatur pariatur et, nesciunt quaerat sequi corporis ex aliquam perspiciatis omnis optio dolore ipsa, laboriosam tempora dicta harum impedit. Sapiente rem impedit deleniti dolores ducimus architecto dolor, fugiat cupiditate delectus iure ea sequi hic repellat consequatur sit. Non amet praesentium debitis libero alias illo aspernatur, doloremque modi laudantium voluptatibus veritatis porro! Alias neque ducimus voluptas velit labore consequatur, atque cumque ratione a sunt ipsam sequi quia animi consectetur. Modi, ducimus asperiores fuga porro explicabo eos quidem nulla illum delectus laboriosam velit sint odit saepe recusandae omnis magni corporis.</p></div>
</section>

<section class="message">
<div ><p class="message_user">Tonio</p>
<p class="message_text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Libero expedita, nulla earum aspernatur quaerat aliquid maiores perspiciatis illum dignissimos? Facere cupiditate, esse similique harum vitae at impedit dolor reiciendis architecto quae maiores dolore distinctio rem maxime necessitatibus voluptatem. Officiis praesentium facilis expedita totam nemo, exercitationem voluptatibus, vitae blanditiis ratione, reprehenderit ea commodi perspiciatis maxime non natus harum id est molestiae. Non voluptas illum natus, ab voluptate debitis qui aut culpa, ratione inventore quasi minima ex quibusdam delectus asperiores deserunt quidem ea repellendus praesentium iusto quia nobis! Recusandae ipsum impedit nihil quo similique, quidem maxime illo quia adipisci aliquid ratione et unde expedita asperiores eaque commodi reiciendis vitae quos dolorum neque hic, perferendis accusamus corrupti. Debitis a, cupiditate omnis explicabo accusantium ea in molestias labore quibusdam ratione sint sed aliquid temporibus aliquam odit suscipit quaerat laborum nostrum eaque officia vel totam alias saepe incidunt! Earum, necessitatibus rem et veniam doloremque ducimus sunt quae dolorem ullam quod, vel temporibus modi. Porro nemo labore temporibus aspernatur pariatur et, nesciunt quaerat sequi corporis ex aliquam perspiciatis omnis optio dolore ipsa, laboriosam tempora dicta harum impedit. Sapiente rem impedit deleniti dolores ducimus architecto dolor, fugiat cupiditate delectus iure ea sequi hic repellat consequatur sit. Non amet praesentium debitis libero alias illo aspernatur, doloremque modi laudantium voluptatibus veritatis porro! Alias neque ducimus voluptas velit labore consequatur, atque cumque ratione a sunt ipsam sequi quia animi consectetur. Modi, ducimus asperiores fuga porro explicabo eos quidem nulla illum delectus laboriosam velit sint odit saepe recusandae omnis magni corporis.</p></div>
</section>
    

</main>